version: 2

sources:
  - name: reddit
    description: "Raw data from Reddit RSS feeds"
    database: reddit_db
    schema: raw
    tables:
      - name: reddit_posts
        description: "Raw JSON data loaded from Python"